/*------------------------------------------------------------------
* Copyright (c) Information Builders, Inc.  All rights reserved.
*
* _Name_        ===> ar_v1/arstrings.js
* _Description_ ===>
*
* _History_:
*  Date  Time Who Proj       Project Title
* ====== ==== === ====== ===========================================
* 180220 0915 wjf 200246 AHML: Unify JSON output
* 180125 1355 txk 199855 The message that is displayed when the graph display number
* 171106 1801 asb 197617 NLV:No data to Graph message should be translated
* 171016 1639 ppl 196755 Show prompt in Visualization >True and False strings nee
* 170812 1215 wjf 191268 Choropleth\Proportional: lasso on ESRI maps throwing Script
* 170808 1042 bjd 190666 NLV: A string, "MISSING" needs to be extracted for translat
* 170804 1045 bjd 190666 NLV: A string, "MISSING" needs to be extracted for translat
* 170705 1133 wjf 188889 Vis: Run time menu - Funnel functionality is not working pr
* 170321 1019 wjf 168489 NFR:Filtering in Active Reports doesn't update totals
* 161107 0856 wjf 185566 AHTML Chart not displaying Pie feeler lines at run-time
* 160921 0949 iys 184736 Aggregation title is displayed as "Undefined" in chart tool
* 160919 1157 iys 184736 Aggregation title is displayed as "Undefined" in chart tool
* 160623 1204 wjf 174265 Visualization:Drill menu consolidation for cases with multi
* 160609 1321 wjf 172017 Handle bucket graphs with no data and EMPTYREPORT=ON
* 160526 0932 wjf 181231 Drop-down in chart toolbar (1st button) missing tooltip
* 160115 1034 bjd 172735 AHTML: Cache: Restore Original is not working good once rep
* 150915 1051 bjd 136022 AHTML: NFR: Export to PDF Option
* 150914 1523 bjd 136022 AHTML: NFR: Export to PDF Option
* 150506 1103 wjf 167100 IDIS: Drill Down and Drill thru support from the output
* 150505 1014 wjf 167100 IDIS: Drill Down and Drill thru support from the output
* 150401 1652 wjf 165611 AHTML: GRID: Add menu options using graph tooltips style
* 141015 1122 bjd 161629 MED: project stamps in minified js files
* 140621 2256 wjf 159606 AHTML/FLEX Add support for Not BETWEEN to filter controls
* 140605 1138 wjf 158619 AHTML and Flex: manage source code in MedProj
* 140604 0908 wjf 158619 AHTML and Flex: manage source code in MedProj
* 140603 1341 wjf 158619 AHTML and Flex: manage source code in MedProj
* 140603 1323 wjf 158619 AHTML and Flex: manage source code in MedProj
*
* END %&$
*-------------------------------------------------------------------*/
/*Copyright 1996-2011 Information Builders, Inc. All rights reserved.*/
if(typeof(ActiveJSRevision)=="undefined") var ActiveJSRevision=new Object();
ActiveJSRevision["arstrings"]="$Revision: 20180220.0915 $";
ibiMsgStr = {
    "mobiletitle": "<%^Active Tech%>",
    "chartSelection": "<%^Chart Type%>",
    "go": "<%^Done%>",
    "back": "<%^Back%>",
    "cancel": "<%^Cancel%>",
    "fsr": "<%^Fullscreen%>",
    "ogv": "<%^Original View%>",
    "del": "<%^Delete%>",
    "fil": "<%^File%>",
    "add": "<%^Add Condition%>",
    "con": "<%^Condition%>",
    "val": "<%^Values%>",
    "are": "<%^All records%>",
    "res": "<%^Restore%>",
    "cal": "<%^Calculate%>",
    "hid": "<%^Hide%>",
    "pot": "<%^% of Total%>",
    "pct": "<%^Percent%>",
    "acd": "<%^Accordion%>",
    "rso": "<%^Restore Original%>",
    "OrigChart": "<%^Original Chart%>",
    "hdc": "<%^Hide Column%>",
    "dsc": "<%^Show Column%>",
    "sas": "<%^Sort Ascending%>",
    "sds": "<%^Sort Descending%>",
    "flt": "<%^Filter%>",
    "clr": "<%^Clear%>",
    "cla": "<%^Clear All%>",
    "ans": "<%^Operator: AND%>",
    "ors": "<%^Operator: OR%>",
    "cpa": "<%^Collapse All%>",
    "exa": "<%^Expand All%>",
    "uhc": "<%^Show Columns%>",
    "uha": "<%^Show All%>",
    "ufa": "<%^Unfreeze All%>",
    "dft": "<%^Default%>",
    "shr": "<%^Show Records%>",
    "sha": "<%^Show All%>",
    "eq": "<%^Equals%>",
    "neq": "<%^Not equal%>",
    "grt": "<%^Greater than%>",
    "gre": "<%^Greater than or equal to%>",
    "lss": "<%^Less than%>",
    "lse": "<%^Less than or equal to%>",
    "bet": "<%^Between%>",
    "nbt": "<%^Not Between%>",
    "inl": "<%^In list%>",
    "cnt": "<%^Contains%>",
    "ctm": "<%^Contains (match case)%>",
    "omt": "<%^Omits%>",
    "omm": "<%^Omits (match case)%>",
    "cou": "<%^Count%>",
    "cds": "<%^Distinct%>",
    "fzc": "<%^Freeze Column%>",
    "fpg": "<%^First Page%>",
    "lpg": "<%^Last Page%>",
    "ppg": "<%^Previous Page%>",
    "npg": "<%^Next Page%>",
    "rect": "<%^Records%>",
    "fls": "<%^Filter Selection%>",
    "olr": "<%^Filtered only%>",
    "exx": "<%^XML (Excel)%>",
    "exp": "<%^Export%>",
    "exh": "<%^HTML%>",
    "exc": "<%^CSV (comma delim)%>",
    "tac": "<%^Switch to%>",
    "tac1": "<%^Accordion%>",
    "tac2": "<%^Flat%>",
    "cexp": "<%^Expanded%>",
    "frp": "<%^ for Report %>",
    "mset": "<%^Export to%>",
    "mspt": "<%^PowerPoint%>",
    "msex": "<%^Excel%>",
    "mswd": "<%^Word%>",
    "tctext": "<%^Toggle Calculation Type%>",
    "sctext": "<%^Select Calculation Type%>",
    "xpem": "<%^Send as E-mail%>",
    "xsar": "<%^Save Changes%>",
    "pmsre": "<%^Save Report%>",
    "sesub": "<%^Active Report%>",
    "seatt": "<%^See Attachment%>",
    "pgtotal": "<%^Total%>",
    "cfil": "<%^Filtered%>",
    "wt01": "<%^Window%>",
    "wt02": "<%^Tabs%>",
    "wt03": "<%^Cascade%>",
    "wt04": "<%^Tile Vertically%>",
    "wt05": "<%^Tile Horizontally%>",
    "irsum": "<%^Sum%>",
    "iravg": "<%^Avg%>",
    "irmin": "<%^Min%>",
    "irmax": "<%^Max%>",
    "ircnt": "<%^Cnt%>",
    "ircnd": "<%^Cnt Dist%>",
    "pbottext": "<%^Move to Bottom%>",
    "ptoptext": "<%^Move to Top%>",
    "ctot": "<%^Total%>",
    "psmsg": "<%^Please Wait%>",
    "addnmsg": "<%^Enter Comment%>",
    "ngbmsg": "<%^Please select a Group By value.%>",
    "naymsg": "<%^Please select at least one Y value.%>",
    "mxwnr": "<%^The maximum number of windows have been reached.%>",
    "Layouts": "<%^Layouts%>",
    "Chart": "<%^Chart%>",
    "Charts": "<%^Charts%>",
    "Data": "<%^Data%>",
    "Series": "<%^Series%>",
    "Pivot": "<%^Pivot%>",
    "Filter": "<%^Filter%>",
    "Grid": "<%^Grid%>",
    "Report": "<%^Report%>",
    "pmsav": "<%^Please enter a filename to save the report.%>",
    "pmsave": "<%^Please enter a filename to email the report.%>",
    "pmov": "<%^Replace file if exist.%>",
    "pmsac": "<%^Save changes.%>",
    "pmop": "<%^Open Browser when done.%>",
    "Prompt": "<%^Prompt%>",
    "pmfl": "<%^Filtered Only%>",
    "addnotes": "<%^Add Comment%>",
    "pmsal": "<%^Selected Grid Only.%>",
    "all": "<%^[All]%>",
    "toc": "<%^Table of Contents%>",
    "visual": "<%^Visualize%>",
    "gblf": "<%^Global Filter%>",
    "addy": "<%^Add (Y)%>",
    "remy": "<%^Remove%>",
    "agg": "<%^Aggregation%>",
    "lnk1": "<%^UnFreeze%>",
    "lnk2": "<%^Freeze%>",
    "typ": "<%^Type%>",
    "siz": "<%^Size%>",
    "Mini": "<%^Show Window%>",
    "FontFamily": "<%^tahoma,verdana,arial%>",
    "Refresh": "<%^Refresh Data%>",
    "pmpass": "<%^Please enter password to unlock report%>",
    "penter": "<%^Check Password%>",
    "filterc": "<%^Filter Cell%>",
    "filtercr": "<%^Remove Cell Filter%>",
    "passwrong": "<%^Password is incorrect%>",
    "crtgrid": "<%^Grid%>",
    "crt": "<%^Chart%>",
    "crtpie": "<%^Pie%>",
    "crtline": "<%^Line%>",
    "crtarea": "<%^Area%>",
    "crtbar": "<%^Bar%>",
    "crtcol": "<%^Column%>",
    "crtscat": "<%^Scatter%>",
    "crtother": "<%^Other%>",
    "crtroll": "<%^Rollup%>",
    "crtpvt": "<%^Pivot%>",
    "crtpivot": "<%^Pivot (Cross Tab)%>",
    "crtpvt1": "<%^Across%>",
    "crtpvt2": "<%^Group By%>",
    "crtgby": "<%^Group By (X)%>",
    "crtxax": "<%^Y Axis%>",
    "crtadv": "<%^Advanced%>",
    "crtadm": "<%^Advanced Chart%>",
    "ok": "<%^Ok%>",
    "password": "<%^Password:%>",
    "expreport": "<%^Report expiration date has been passed.%>",
    "shwnotes": "<%^Show Notes%>",
    "edtnotes": "<%^Edit Notes%>",
    "passpmt": "<%^Report is Password Protected%>",
    "savepmt": "<%^Save as%>",
    "stacked": "<%^Stacked%>",
    "regress": "<%^Trend%>",
    "nwbt": "<%^New%>",
    "detail": "<%^Detail%>",
    "colorby": "<%^Arrange By%>",
    "xaxis": "<%^X Axis%>",
    "yaxis": "<%^Y Axis%>",
    "ecfilt": "<%^Filter Chart%>",
    "clrt": "<%^Color Scheme%>",
    "crtcflt": "<%^Remove Filter%>",
    "untcflt": "<%^Undo Filter%>",
    "hlg": "<%^Highlight%>",
    "hlgv": "<%^Highlight Value%>",
    "hlgr": "<%^Highlight Row%>",
    "hlgs": "<%^Highlight Selection%>",
    "hlgu": "<%^Unhighlight Row%>",
    "hlga": "<%^Unhighlight All%>",
    "dtran": "<%^Enable Transitions%>",
    "snotes": "<%^Expand%>",
    "hsnotes": "<%^Hide Indicator%>",
    "gotopage": "<%^Goto Page%>",
    "shead": "<%^Hide Subtitles%>",
    "hhead": "<%^Show Subtitles%>",
    "coledit": "<%^Edit Columns%>",
    "notes": "<%^Notes%>",
    "comments": "<%^Comments%>",
    "top": "<%^Top%>",
    "top3": "<%^Top 3%>",
    "top5": "<%^Top 5%>",
    "top10": "<%^Top 10%>",
    "topremove": "<%^Clear Top%>",
    "chfail": "<HTML><HEAD><TITLE><%^Request Failed%></TITLE></HEAD><BODY><H2><%^Request failed. Your session may have expired%></H2></BODY></HTML>",
    "nodata": "<span style='font-weight:bold;color:white;font-size:16px;font-family:<%^tahoma,verdana,arial%>'><%^No data to chart%><\/span>",
    "nodatagraph": "<%^No data to Graph%>",
    "paglinetext": "<%^%rcs of %trcs records, Page %inds of %pgs%><span id='smsg%tn'><\/span>",
    "NeedActiveXMsg": "<%^To use this feature you must enable ActiveX in your browser security settings.%><%^\nPlease enable 'Initialize and script ActiveX controls not marked as safe' in your Security Settings.%>",
    "getmoredata": "<%^Getting more Data%>",
    "sorting": "<%^Sorting%>",
    "ssort": "<%^Select Sort Order%>",
    "calculating": "<%^Calculating%>",
    "servererr": "<%^Server Error:%>",
    "gridtool": "<%^Grid Tool%>",
    "charttool": "<%^Chart/Rollup Tool%>",
    "pivottool": "<%^Pivot Tool%>",
    "colorder": "<%^Column Order%>",
    "sortorder": "<%^Sort Order%>",
    "subtotal": "<%^Subtotal%>",
    "measure": "<%^Measure%>",
    "draghere": "<%^Drag Column Here%>",
    "groupsort": "<%^Group sort columns%>",
    "print": "<%^Print%>",
    "none": "<%^None%>",
    "lic": "<%^Active Technologies Trial Version%>",
    "lic2": "<%^Active Technologies Trial Version%>",
    "nolic":"<%^No valid license key found for Active Reports (AHTML).  Please contact your WebFOCUS administrator.%>",
    "columns": "<%^Columns%>",
    "pop": "<%^Unable to open new browser window.  Please disable any popup blocker to use this feature.%>",
    "dragToResize": "<%^Drag this handle to resize the component%>",

    "DfltColumn": "<%^Default Column%>",
    "Column2D": "<%^Column 2D%>",
    "Column3D": "<%^Column 3D%>",
    "MSColumn2D": "<%^Multi-series Column 2D%>",
    "MSColumn3D": "<%^Multi-series Column 3D%>",
    "StackedColumn2D": "<%^ Stacked Column 2D%>",
    "StackedColumn3D": "<%^ Stacked Column 3D%>",
    "ScrollColumn2D": "<%^Scroll Multi-series Column 2D%>",
    "ScrollStackedColumn2D": "<%^Scroll Stacked Column 2D%>",
    "LogMSColumn2D": "<%^Logarithmic Multi-series Column 2D%>",
    "InverseMSColumn2D": "<%^Inverse y-Axis Multi-series Column 2D%>",

    "Bar2D": "<%^Bar 2D%>",
    "MSBar2D": "<%^ Multi-series Bar 2D%>",
    "MSBar3D": "<%^ Multi-series Bar 3D%>",
    "StackedBar2D": "<%^Stacked Bar 2D%>",
    "StackedBar3D": "<%^Stacked Bar 3D%>",

    "DfltPie": "<%^Default Pie%>",
    "Pie2D": "<%^Pie 2D%>",
    "Pie3D": "<%^Pie 3D%>",
    "Doughnut2D": "<%^Doughnut 2D%>",
    "Doughnut3D": "<%^Doughnut 3D%>",

    "DfltLine": "<%^Default Line%>",
    "Line": "<%^Line 2D%>",
    "MSLine": "<%^Multi-series Line 2D%>",
    "LogMSLine": "<%^Logarithmic Multi-series Line 2D%>",
    "ScrollLine2D": "<%^Scroll Multi-series Line 2D%>",
    "InverseMSLine": "<%^Inverse Y-axis Multi-series Line 2D%>",
    "Spline": "<%^Spline%>",
    "MSSpline": "<%^ Multi-series Spline%>",

    "Area2D": "<%^Area 2D%>",
    "MSArea": "<%^Multi-series Area 2D%>",
    "StackedArea2D": "<%^Stacked Area 2D%>",
    "ScrollArea2D": "<%^Scroll Multi-series Area 2D%>",
    "InverseMSArea": "<%^Inverse Y-axis Multi-series Area%>",
    "SplineArea": "<%^Spline Area%>",
    "MSSplineArea": "<%^Multi-series Spline Area%>",

    "DfltScatter": "<%^Default Scatter%>",
    "Scatter": "<%^Scatter(XY Plot)%>",
    "Bubble": "<%^Bubble%>",

    "Funnel": "<%^Funnel%>",
    "Pyramid": "<%^Pyramid%>",
    "Radar": "<%^Radar%>",
    "Loading": "<%^Loading...%>",
    "by": "<%^BY%>",
    "VBar": "<%^VBar%>",
    "Errorbar": "<%^Errorbar%>",
    "Bar": "<%^Bar%>",
    "Stacked_Bar": "<%^Stacked Bar%>",
    "Percent_Bar": "<%^Percent Bar%>",
    "Column": "<%^Column%>",
    "Stacked_Column": "<%^Stacked Column%>",
    "Percent_Column": "<%^Percent Column%>",
    "Column_Depth": "<%^Column Depth%>",
    "Stacked_Depth": "<%^Stacked Depth%>",
    "Percent_Depth": "<%^Percent Depth%>",
    "3D_Column": "<%^3D Column%>",
    "Pie_Bevel": "<%^Pie (Bevel)%>",
    "Pie": "<%^Pie%>",
    "Pie_with_Depth": "<%^Pie with Depth%>",
    "Donut_Cylinder": "<%^Donut (Cylinder)%>",
    "Donut_with_Depth": "<%^Donut with Depth%>",
    "Donut_Bevel": "<%^Donut (Bevel)%>",
    "Donut": "<%^Donut%>",
    "Curved_Markers": "<%^Curved + Markers%>",
    "Straight_Markers": "<%^Straight + Markers%>",
    "Curved": "<%^Curved%>",
    "Straight": "<%^Straight%>",
    "Step": "<%^Step%>",
    "Area": "<%^Area%>",
    "vLine": "<%^Line%>",
    "Stacked_Area": "<%^Stacked Area%>",
    "Percent_Area": "<%^Percent Area%>",
    "3D_Area": "<%^3D Area%>",
    "Scatters": "<%^Scatters%>",
    "Pyramid_1": "<%^Pyramid 1%>",
    "Heatmap": "<%^Heatmap%>",
    "Waterfall": "<%^Waterfall%>",
    "Histogram": "<%^Histogram%>",
    "Polar": "<%^Polar%>",
    "Radar_Line": "<%^Radar Line%>",
    "Radar_Area": "<%^Radar Area%>",
    "Tag_Cloud": "<%^Tag Cloud%>",
    "Map": "<%^Map%>",
    "exfilt": "<%^Exclude from Chart%>",
    "srowtot":"<%^Show Row Total%>",
    "scoltot":"<%^Show Column Total%>",
    "snoprint":"<%^Show Hidden Fields%>",
    "drillup":"<%^Drill up to%>",
    "drilldown":"<%^Drill down to%>",
    "menuOptions":"<%^More Options%>",
    "exlExportMsg": "<html><head><title><%^Exporting...%></title></head><body><center><p><%^Please wait...%></center></br><center><%^Exporting to EXCEL...%></center></p></body></html>",
    "expdf":"PDF",
    "restOrgMsg":"<%^Warning: Original sort could not be determined%>",
    "ech":"Enter Calculation Here:",
    "fldn":"Field Name:",
    "addf":"Add Field",
    "edtf":"Edit Field",
    "showData":"Show Chart Data",
    "showFilter":"Show Filter",
    "missing": "<%^MISSING%>",
    "nofilt":"<%^Filtering Not Available%>",
    "true":"<%^true%>",
    "false":"<%^false%>",
    "too_many_bars":"<%^too many bars%>",
    "too_many_series":"<%^too many series%>",
    "too_many_points":"<%^too many points%>"
};

